### ISSUE TITLE
CGDisplayIOServicePort deprecated in OSX 10.9

### ISSUE THREAD

**Issue by Kalvin126** [jontaylor/DDC-CI-Tools-for-OS-X#2]
CGDisplayIOServicePort deprecated has been OSX 10.9. Is there a work around?

**Comment by sodabrew** [comment]
Does this provide an appropriate workaround? http://stackoverflow.com/a/21655038/3483097

**Comment by Kalvin126** [comment]
This does not work on my setup, a retina MacBook pro 13 connected to a dell u2414h. It works on the built in lcd though

**Comment by Kalvin126** [comment]
Doing some debugging, I have found that IOFBGetI2CInterfaceCount returns a bus count of 0. This was used in ddc.c at line 238. Thus, no buses are available to send requests. I have verified that DDC / CI is enabled on my Dell monitors.

**Comment by ryanrhee** [comment]
Same issue here, bus count is 0.

**Comment by Kalvin126** [comment]
Got the work around provided by @sodabrew  to work after much massaging
