### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by pitkley** [jontaylor/DDC-CI-Tools-for-OS-X#3]
@jontaylor: I'm currently in the progress of writing a tool which is based on a DDC-library distributed by @kfix for their tool [ddcctl](https://github.com/kfix/ddcctl).

This library in turn seems to be based on your code, though heavily modified by (I assume) [SJ_UnderWater](http://www.tonymacx86.com/members/sj_underwater/) for their tool [DDC Panel](http://www.tonymacx86.com/graphics/90077-controlling-your-monitor-osx-ddc-panel.html). Both @kfix and SJ_UnderWater licensed their own code under GPLv3, apparently excluding the files `DDC.{c,h}`.

Would it be possible for you to add a license to your code which allows for (non-commercial) distribution and modification?

Thank you for your time!
Best regards.

**Comment by jontaylor** [comment]
Thanks. I have added a GPLv3 license so that its compatible with the others.

**Comment by pitkley** [comment]
Thank you very much for your fast reaction, it is greatly appreciated!

Have a great day!
